"""ORM 模型汇总。

Alembic 的 autogenerate 依赖本模块把全部模型导入到 `Base.metadata`，
因此**新增模型后必须在这里导出**，否则迁移会漏表。
"""

from app.db.models.audit import AuditLog
from app.db.models.batch import (
    ExpenseRow,
    FieldAvailability,
    FieldStatus,
    FileVersion,
    ParseStatus,
    RevisionReason,
    RowResult,
)
from app.db.models.config import RuleConfig, SchemaMapping, SchemaMappingVersion
from app.db.models.detection import (
    CorrelationFindingRow,
    DetectionConfig,
    DetectionRequest,
    DetectionRun,
    DetectorKind,
)
from app.db.models.findings import (
    CapabilityDeclaration,
    CapabilityStatus,
    CorrelationFinding,
    EvidenceStep,
    Finding,
    Review,
    ReviewDecision,
    ReviewPlanRequest,
    ReviewSamplingConfig,
    ReviewSamplingPlan,
    RuleKind,
    SamplingAudit,
    SamplingReview,
    SamplingReviewDecision,
)
from app.db.models.grading import (
    GradingConfig,
    GradingDisposition,
    GradingItem,
    GradingItemRow,
    GradingRequest,
    GradingRun,
    GradingRunStatus,
    GradingSourceKind,
)
from app.db.models.investigation import (
    InvestigationActionKind,
    InvestigationOutcome,
    InvestigationProviderKind,
    InvestigationRequest,
    InvestigationResult,
    InvestigationRun,
    PiiKind,
    PiiToken,
)
from app.db.models.policy import (
    PolicyChunk,
    PolicyClause,
    PolicyDocument,
    PolicyDocumentIndex,
    PolicyDocumentIndexStatus,
    PolicyDocumentStatus,
    PolicyFamily,
    PolicyIndexGeneration,
    PolicyIndexGenerationStatus,
    PolicyIndexJob,
    PolicyIndexJobStatus,
    PolicyIndexOperation,
    PolicySourceBlob,
    RulePolicyBinding,
)
from app.db.models.reports import (
    ReportAttentionGroup,
    ReportCitation,
    ReportCitationStatus,
    ReportExport,
    ReportExportStatus,
    ReportItem,
    ReportParseError,
    ReportRequest,
    ReportRun,
    ReportRunStatus,
)
from app.db.models.tenancy import AppUser, Role, Tenant, UserSession
from app.db.models.validation import ValidationDependency, ValidationRun, ValidationRunStatus

__all__ = [
    "AppUser",
    "AuditLog",
    "CapabilityDeclaration",
    "CapabilityStatus",
    "CorrelationFinding",
    "CorrelationFindingRow",
    "DetectionConfig",
    "DetectionRequest",
    "DetectionRun",
    "DetectorKind",
    "EvidenceStep",
    "ExpenseRow",
    "FieldAvailability",
    "FieldStatus",
    "FileVersion",
    "Finding",
    "GradingConfig",
    "GradingDisposition",
    "GradingItem",
    "GradingItemRow",
    "GradingRequest",
    "GradingRun",
    "GradingRunStatus",
    "GradingSourceKind",
    "InvestigationActionKind",
    "InvestigationOutcome",
    "InvestigationProviderKind",
    "InvestigationRequest",
    "InvestigationResult",
    "InvestigationRun",
    "ParseStatus",
    "PiiKind",
    "PiiToken",
    "PolicyChunk",
    "PolicyClause",
    "PolicyDocument",
    "PolicyDocumentIndex",
    "PolicyDocumentIndexStatus",
    "PolicyDocumentStatus",
    "PolicyFamily",
    "PolicyIndexGeneration",
    "PolicyIndexGenerationStatus",
    "PolicyIndexJob",
    "PolicyIndexJobStatus",
    "PolicyIndexOperation",
    "PolicySourceBlob",
    "ReportAttentionGroup",
    "ReportCitation",
    "ReportCitationStatus",
    "ReportExport",
    "ReportExportStatus",
    "ReportItem",
    "ReportParseError",
    "ReportRequest",
    "ReportRun",
    "ReportRunStatus",
    "Review",
    "ReviewDecision",
    "ReviewPlanRequest",
    "ReviewSamplingConfig",
    "ReviewSamplingPlan",
    "RevisionReason",
    "Role",
    "RowResult",
    "RuleConfig",
    "RuleKind",
    "RulePolicyBinding",
    "SamplingAudit",
    "SamplingReview",
    "SamplingReviewDecision",
    "SchemaMapping",
    "SchemaMappingVersion",
    "Tenant",
    "UserSession",
    "ValidationDependency",
    "ValidationRun",
    "ValidationRunStatus",
]
