"""ORM 模型汇总。

Alembic 的 autogenerate 依赖本模块把全部模型导入到 `Base.metadata`，
因此**新增模型后必须在这里导出**，否则迁移会漏表。
"""

from app.db.models.audit import AuditLog
from app.db.models.batch import (
    ExpenseRow,
    FieldAvailability,
    FieldStatus,
    FileVersion,
    ParseStatus,
    RevisionReason,
    RowResult,
)
from app.db.models.config import RuleConfig, SchemaMapping, SchemaMappingVersion
from app.db.models.findings import (
    CapabilityDeclaration,
    CapabilityStatus,
    CorrelationFinding,
    EvidenceStep,
    Finding,
    Review,
    ReviewDecision,
    RuleKind,
    SamplingAudit,
)
from app.db.models.policy import (
    PolicyChunk,
    PolicyClause,
    PolicyDocument,
    PolicyDocumentIndex,
    PolicyDocumentIndexStatus,
    PolicyDocumentStatus,
    PolicyFamily,
    PolicyIndexGeneration,
    PolicyIndexGenerationStatus,
    PolicyIndexJob,
    PolicyIndexJobStatus,
    PolicyIndexOperation,
    PolicySourceBlob,
    RulePolicyBinding,
)
from app.db.models.reports import (
    ReportAttentionGroup,
    ReportCitation,
    ReportCitationStatus,
    ReportExport,
    ReportExportStatus,
    ReportItem,
    ReportParseError,
    ReportRun,
    ReportRunStatus,
)
from app.db.models.tenancy import AppUser, Role, Tenant, UserSession
from app.db.models.validation import ValidationDependency, ValidationRun, ValidationRunStatus

__all__ = [
    "AppUser",
    "AuditLog",
    "CapabilityDeclaration",
    "CapabilityStatus",
    "CorrelationFinding",
    "EvidenceStep",
    "ExpenseRow",
    "FieldAvailability",
    "FieldStatus",
    "FileVersion",
    "Finding",
    "ParseStatus",
    "PolicyChunk",
    "PolicyClause",
    "PolicyDocument",
    "PolicyDocumentIndex",
    "PolicyDocumentIndexStatus",
    "PolicyDocumentStatus",
    "PolicyFamily",
    "PolicyIndexGeneration",
    "PolicyIndexGenerationStatus",
    "PolicyIndexJob",
    "PolicyIndexJobStatus",
    "PolicyIndexOperation",
    "PolicySourceBlob",
    "ReportAttentionGroup",
    "ReportCitation",
    "ReportCitationStatus",
    "ReportExport",
    "ReportExportStatus",
    "ReportItem",
    "ReportParseError",
    "ReportRun",
    "ReportRunStatus",
    "Review",
    "ReviewDecision",
    "RevisionReason",
    "Role",
    "RowResult",
    "RuleConfig",
    "RuleKind",
    "RulePolicyBinding",
    "SamplingAudit",
    "SchemaMapping",
    "SchemaMappingVersion",
    "Tenant",
    "UserSession",
    "ValidationDependency",
    "ValidationRun",
    "ValidationRunStatus",
]
