/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login
     * @description 登录并下发会话 cookie。
     */
    post: operations["auth_login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout
     * @description 登出。
     *
     *     只撤销**本次请求所用的那一个**会话（`auth.session_id` 由认证依赖
     *     精确解析得出），因此同一用户在其它设备上的登录不受影响。
     *
     *     服务端标记 `revoked_at`（UPDATE 而非 DELETE —— 留痕），
     *     同时清掉浏览器 cookie。
     */
    post: operations["auth_logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Me
     * @description 返回当前登录用户。前端用它做路由守卫。
     */
    get: operations["auth_me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/batches": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List
     * @description 列出当前租户批次。
     */
    get: operations["batches_list"];
    put?: never;
    /**
     * Import
     * @description 上传 Excel 并创建或复用文件版本。
     */
    post: operations["batches_import"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/batches/{file_version_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Detail
     * @description 读取批次详情。
     */
    get: operations["batches_detail"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/batches/{file_version_id}/field-availability": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Field Availability
     * @description 返回当前解析版本的全部统一字段可用性。
     */
    get: operations["batches_field_availability"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/batches/{file_version_id}/findings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Findings */
    get: operations["batches_findings"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/batches/{file_version_id}/parse": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Parse
     * @description 按指定不可变映射版本原子解析批次。
     */
    post: operations["batches_parse"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/batches/{file_version_id}/parse-errors": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Parse Errors
     * @description 分页读取解析失败行，保留原始证据链。
     */
    get: operations["batches_parse_errors"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/batches/{file_version_id}/revisions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Revision */
    post: operations["batches_create_revision"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/batches/{file_version_id}/validate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Validate */
    post: operations["batches_validate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/batches/{file_version_id}/validation": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Validation */
    get: operations["batches_validation"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness
     * @description 存活探针。刻意不碰任何外部依赖。
     */
    get: operations["health_liveness"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness
     * @description 就绪探针。并发探测各依赖，任一不可用即整体未就绪。
     */
    get: operations["health_readiness"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/rules": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List */
    get: operations["rules_list"];
    /** Save */
    put: operations["rules_save"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/schema-mappings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List
     * @description 返回当前批次表头可精确复用的映射版本。
     */
    get: operations["schema-mappings_list"];
    /**
     * Save
     * @description 追加一个不可变映射版本；相同内容重试幂等复用。
     */
    put: operations["schema-mappings_save"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AvailabilityEvidence
     * @description 不含样本值的版本化字段可用性证据。
     */
    AvailabilityEvidence: {
      direct: components["schemas"]["DirectAvailabilityEvidence"];
      inference: components["schemas"]["InferenceAvailabilityEvidence"];
      /**
       * Mapping Version Id
       * Format: uuid
       */
      mapping_version_id: string;
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: 1;
      /**
       * Selected Basis
       * @enum {string}
       */
      selected_basis: "direct" | "inference" | "none";
      /** Total Rows */
      total_rows: number;
    };
    /** AvailabilityThresholdsRequest */
    AvailabilityThresholdsRequest: {
      /**
       * Available Min Non Null Rate
       * @default 0.80
       */
      available_min_non_null_rate: number | string;
      /**
       * Inferred Min Success Rate
       * @default 0.80
       */
      inferred_min_success_rate: number | string;
    };
    /** AvailabilityThresholdsResponse */
    AvailabilityThresholdsResponse: {
      /** Available Min Non Null Rate */
      available_min_non_null_rate: string;
      /** Inferred Min Success Rate */
      inferred_min_success_rate: string;
    };
    /**
     * BatchDetailResponse
     * @description 批次详情响应。
     */
    BatchDetailResponse: {
      /** Content Hash */
      content_hash: string;
      /**
       * File Version Id
       * Format: uuid
       */
      file_version_id: string;
      /** Filename */
      filename: string;
      /** Row Count */
      row_count: number;
      /** Rows */
      rows: components["schemas"]["ExpenseRowResponse"][];
      /**
       * Uploaded At
       * Format: date-time
       */
      uploaded_at: string;
      /**
       * Uploaded By
       * Format: uuid
       */
      uploaded_by: string;
    };
    /**
     * BatchImportResponse
     * @description 批次导入响应。
     */
    BatchImportResponse: {
      /** Content Hash */
      content_hash: string;
      /**
       * File Version Id
       * Format: uuid
       */
      file_version_id: string;
      /** Filename */
      filename: string;
      /** Reused Existing */
      reused_existing: boolean;
      /** Row Count */
      row_count: number;
      /** Stored Rows */
      stored_rows: number;
      /**
       * Uploaded At
       * Format: date-time
       */
      uploaded_at: string;
      /**
       * Uploaded By
       * Format: uuid
       */
      uploaded_by: string;
    };
    /**
     * BatchSummaryResponse
     * @description 批次列表项。
     */
    BatchSummaryResponse: {
      /** Content Hash */
      content_hash: string;
      /**
       * File Version Id
       * Format: uuid
       */
      file_version_id: string;
      /** Filename */
      filename: string;
      /** Row Count */
      row_count: number;
      /**
       * Uploaded At
       * Format: date-time
       */
      uploaded_at: string;
      /**
       * Uploaded By
       * Format: uuid
       */
      uploaded_by: string;
    };
    /** Body_batches_import */
    Body_batches_import: {
      /** File */
      file: string;
    };
    /**
     * ConstantInferenceRule
     * @description 固定值推断；首版只允许推断币种。
     */
    ConstantInferenceRule: {
      /** Rule Id */
      rule_id: string;
      /**
       * Target Field
       * @constant
       */
      target_field: "currency";
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "constant";
      /** Value */
      value: string;
    };
    /** CreateRevisionRequest */
    CreateRevisionRequest: {
      reason: components["schemas"]["RevisionRequestReason"];
    };
    /** CreateRevisionResponse */
    CreateRevisionResponse: {
      /**
       * File Version Id
       * Format: uuid
       */
      file_version_id: string;
      /** Mapping Version Id */
      mapping_version_id: string | null;
      /**
       * Parse Status
       * @enum {string}
       */
      parse_status: "unparsed" | "parsed" | "parsed_with_errors";
      reason: components["schemas"]["RevisionRequestReason"];
      /** Reused Existing */
      reused_existing: boolean;
      /** Revision No */
      revision_no: number;
      /**
       * Root File Version Id
       * Format: uuid
       */
      root_file_version_id: string;
      /**
       * Source File Version Id
       * Format: uuid
       */
      source_file_version_id: string;
    };
    /**
     * CurrentUser
     * @description 当前登录用户。
     */
    CurrentUser: {
      /** Permissions */
      permissions: string[];
      role: components["schemas"]["Role"];
      /** Tenant Id */
      tenant_id: string;
      /** User Id */
      user_id: string;
    };
    /**
     * DependencyHealth
     * @description 单个依赖的健康状况。
     */
    DependencyHealth: {
      /** Detail */
      detail?: string | null;
      /** Name */
      name: string;
      status: components["schemas"]["DependencyStatus"];
    };
    /**
     * DependencyStatus
     * @description 依赖状态。
     * @enum {string}
     */
    DependencyStatus: "up" | "down";
    /**
     * DirectAvailabilityEvidence
     * @description 直接映射的非空率证据。
     */
    DirectAvailabilityEvidence: {
      /** Configured */
      configured: boolean;
      /** Non Null Count */
      non_null_count: number;
      /** Non Null Rate */
      non_null_rate: string;
      /** Source Columns */
      source_columns: string[];
      /** Threshold */
      threshold: string;
    };
    /**
     * ErrorDetail
     * @description 错误详情。
     */
    ErrorDetail: {
      /** Code */
      code: string;
      /** Message */
      message: string;
    };
    /**
     * ErrorResponse
     * @description 统一错误响应体。注册进 OpenAPI，使前端能生成对应类型。
     */
    ErrorResponse: {
      error: components["schemas"]["ErrorDetail"];
    };
    /** ExemptionCondition */
    ExemptionCondition: {
      field: components["schemas"]["ExemptionField"];
      /** Value */
      value: string;
    };
    /**
     * ExemptionField
     * @enum {string}
     */
    ExemptionField: "expense_type" | "invoice_type" | "currency";
    /** ExemptionGroup */
    ExemptionGroup: {
      /** All */
      all: components["schemas"]["ExemptionCondition"][];
      /** Exemption Id */
      exemption_id: string;
    };
    /**
     * ExpenseRowResponse
     * @description 原始报销行摘要。
     */
    ExpenseRowResponse: {
      /** Parse Error */
      parse_error: string | null;
      /** Raw Json */
      raw_json: {
        [key: string]: unknown;
      };
      /** Row No */
      row_no: number;
    };
    /** FieldAvailabilityItemResponse */
    FieldAvailabilityItemResponse: {
      evidence: components["schemas"]["AvailabilityEvidence"];
      /** Field Name */
      field_name: string;
      /**
       * Status
       * @enum {string}
       */
      status: "available" | "inferred" | "missing";
    };
    /** FieldAvailabilityResponse */
    FieldAvailabilityResponse: {
      /**
       * File Version Id
       * Format: uuid
       */
      file_version_id: string;
      /** Items */
      items: components["schemas"]["FieldAvailabilityItemResponse"][];
      /**
       * Mapping Version Id
       * Format: uuid
       */
      mapping_version_id: string;
    };
    /**
     * FieldError
     * @description 一个稳定、用户安全的字段解析错误。
     */
    FieldError: {
      /**
       * Code
       * @enum {string}
       */
      code:
        | "REQUIRED_VALUE_MISSING"
        | "AMOUNT_INVALID_FORMAT"
        | "AMOUNT_OUT_OF_RANGE"
        | "DATE_INVALID_FORMAT"
        | "DATE_OUT_OF_RANGE"
        | "TEXT_TOO_LONG"
        | "CURRENCY_INVALID";
      field: components["schemas"]["UnifiedField"];
      /** Message */
      message: string;
      /** Source Column */
      source_column: string;
    };
    /**
     * FieldProvenance
     * @description 不复制原始值的字段证据。
     */
    FieldProvenance: {
      /** Inference Rule Id */
      inference_rule_id?: string | null;
      mode: components["schemas"]["ProvenanceMode"];
      /** Source Columns */
      source_columns: string[];
    };
    /** FindingItemResponse */
    FindingItemResponse: {
      evidence: components["schemas"]["RuleEvidence"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      outcome: components["schemas"]["RuleOutcome"];
      reason_code: components["schemas"]["ReasonCode"];
      /** Reasoning */
      reasoning: string;
      /** Row No */
      row_no: number;
      /** Rule Id */
      rule_id: string;
      rule_kind: components["schemas"]["RuleKind"];
      /** Rule Version */
      rule_version: string | null;
      verdict: components["schemas"]["RowVerdict"];
    };
    /** FindingsResponse */
    FindingsResponse: {
      /**
       * File Version Id
       * Format: uuid
       */
      file_version_id: string;
      /** Items */
      items: components["schemas"]["FindingItemResponse"][];
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total */
      total: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * InferenceAvailabilityEvidence
     * @description 确定性推断的成功率证据。
     */
    InferenceAvailabilityEvidence: {
      /** Configured */
      configured: boolean;
      /** Rule Ids */
      rule_ids: string[];
      /** Success Count */
      success_count: number;
      /** Success Rate */
      success_rate: string;
      /** Threshold */
      threshold: string;
    };
    /** InvoiceDuplicateEvidence */
    InvoiceDuplicateEvidence: {
      /** Duplicate Of File Version Id */
      duplicate_of_file_version_id?: string | null;
      /** Duplicate Of Root File Version Id */
      duplicate_of_root_file_version_id?: string | null;
      /** Duplicate Of Row No */
      duplicate_of_row_no?: number | null;
      /** Exemption Id */
      exemption_id?: string | null;
      /** Invoice No */
      invoice_no?: string | null;
      /**
       * Outcome
       * @enum {string}
       */
      outcome: "flagged" | "unavailable" | "exempted";
      /** Provenance */
      provenance: {
        [key: string]: components["schemas"]["FieldProvenance"];
      };
      reason_code: components["schemas"]["ReasonCode"];
      /** Required Fields */
      required_fields: components["schemas"]["UnifiedField"][];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      rule_kind: "invoice_duplicate";
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: 1;
    };
    /** InvoiceDuplicateRuleDefinition */
    InvoiceDuplicateRuleDefinition: {
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
      /**
       * Exemptions
       * @default []
       */
      exemptions: components["schemas"]["ExemptionGroup"][];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "invoice_duplicate";
      /**
       * Require Direct
       * @default false
       */
      require_direct: boolean;
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: 1;
    };
    /** InvoiceTitleEvidence */
    InvoiceTitleEvidence: {
      /** Allowed Titles Fingerprint */
      allowed_titles_fingerprint?: string | null;
      /** Exemption Id */
      exemption_id?: string | null;
      /** Invoice Title */
      invoice_title?: string | null;
      /**
       * Outcome
       * @enum {string}
       */
      outcome: "flagged" | "unavailable" | "exempted";
      /** Provenance */
      provenance: {
        [key: string]: components["schemas"]["FieldProvenance"];
      };
      reason_code: components["schemas"]["ReasonCode"];
      /** Required Fields */
      required_fields: components["schemas"]["UnifiedField"][];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      rule_kind: "invoice_title";
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: 1;
    };
    /** InvoiceTitleRuleDefinition */
    InvoiceTitleRuleDefinition: {
      /** Allowed Titles */
      allowed_titles: string[];
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
      /**
       * Exemptions
       * @default []
       */
      exemptions: components["schemas"]["ExemptionGroup"][];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "invoice_title";
      /**
       * Require Direct
       * @default false
       */
      require_direct: boolean;
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: 1;
    };
    /** InvoiceTypeAllowance */
    InvoiceTypeAllowance: {
      /** Allowed Invoice Types */
      allowed_invoice_types: string[];
      /** Expense Type */
      expense_type: string;
    };
    /** InvoiceTypeEvidence */
    InvoiceTypeEvidence: {
      /** Allowed Invoice Types Fingerprint */
      allowed_invoice_types_fingerprint?: string | null;
      /** Exemption Id */
      exemption_id?: string | null;
      /** Expense Type */
      expense_type?: string | null;
      /** Invoice Type */
      invoice_type?: string | null;
      /**
       * Outcome
       * @enum {string}
       */
      outcome: "flagged" | "unavailable" | "exempted";
      /** Provenance */
      provenance: {
        [key: string]: components["schemas"]["FieldProvenance"];
      };
      reason_code: components["schemas"]["ReasonCode"];
      /** Required Fields */
      required_fields: components["schemas"]["UnifiedField"][];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      rule_kind: "invoice_type";
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: 1;
    };
    /** InvoiceTypeRuleDefinition */
    InvoiceTypeRuleDefinition: {
      /** Allowances */
      allowances: components["schemas"]["InvoiceTypeAllowance"][];
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
      /**
       * Exemptions
       * @default []
       */
      exemptions: components["schemas"]["ExemptionGroup"][];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "invoice_type";
      /**
       * Require Direct
       * @default false
       */
      require_direct: boolean;
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: 1;
    };
    /** LimitEvidence */
    LimitEvidence: {
      /** Amount */
      amount?: string | null;
      /** Currency */
      currency?: string | null;
      /** Exemption Id */
      exemption_id?: string | null;
      /** Expense Type */
      expense_type?: string | null;
      /** Max Amount */
      max_amount?: string | null;
      /**
       * Operator
       * @default gt
       * @constant
       */
      operator: "gt";
      /**
       * Outcome
       * @enum {string}
       */
      outcome: "flagged" | "unavailable" | "exempted";
      /** Provenance */
      provenance: {
        [key: string]: components["schemas"]["FieldProvenance"];
      };
      reason_code: components["schemas"]["ReasonCode"];
      /** Required Fields */
      required_fields: components["schemas"]["UnifiedField"][];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      rule_kind: "limit";
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: 1;
    };
    /** LimitRuleDefinition */
    LimitRuleDefinition: {
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
      /**
       * Exemptions
       * @default []
       */
      exemptions: components["schemas"]["ExemptionGroup"][];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "limit";
      /**
       * Require Direct
       * @default false
       */
      require_direct: boolean;
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: 1;
      /** Thresholds */
      thresholds: components["schemas"]["LimitThreshold"][];
    };
    /** LimitThreshold */
    LimitThreshold: {
      /** Currency */
      currency: string;
      /** Expense Type */
      expense_type: string;
      /** Max Amount */
      max_amount: string;
    };
    /**
     * LiteralLookupCase
     * @description 字面量包含匹配的一项；列表顺序决定优先级。
     */
    LiteralLookupCase: {
      /** Literal */
      literal: string;
      /** Value */
      value: string;
    };
    /**
     * LiteralLookupInferenceRule
     * @description 从已直接映射字段做 NFKC 字面量包含匹配。
     */
    LiteralLookupInferenceRule: {
      /** Cases */
      cases: components["schemas"]["LiteralLookupCase"][];
      /** Rule Id */
      rule_id: string;
      /** Source Fields */
      source_fields: components["schemas"]["UnifiedField"][];
      target_field: components["schemas"]["UnifiedField"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "literal_lookup";
    };
    /**
     * LivenessResponse
     * @description 存活响应。
     */
    LivenessResponse: {
      /** Status */
      status: string;
    };
    /**
     * LoginRequest
     * @description 登录请求。
     */
    LoginRequest: {
      /** Password */
      password: string;
      /**
       * Tenant Slug
       * @default default
       */
      tenant_slug: string;
      /** Username */
      username: string;
    };
    /** MappingEntryRequest */
    MappingEntryRequest: {
      /** Source Column */
      source_column: string;
      /** Target Field */
      target_field: string;
    };
    /** MappingEntryResponse */
    MappingEntryResponse: {
      /** Source Column */
      source_column: string;
      target_field: components["schemas"]["UnifiedField"];
    };
    /** MappingVersionResponse */
    MappingVersionResponse: {
      availability_thresholds: components["schemas"]["AvailabilityThresholdsResponse"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Created By */
      created_by: string | null;
      /** Currency Aliases */
      currency_aliases: {
        [key: string]: string;
      };
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Inference Rules */
      inference_rules: (
        | components["schemas"]["ConstantInferenceRule"]
        | components["schemas"]["LiteralLookupInferenceRule"]
      )[];
      /** Is Current For Batch */
      is_current_for_batch: boolean;
      /** Mappings */
      mappings: components["schemas"]["MappingEntryResponse"][];
      /** Version */
      version: number;
    };
    /**
     * ParseBatchRequest
     * @description 触发解析所需的不可变映射版本。
     */
    ParseBatchRequest: {
      /**
       * Mapping Version Id
       * Format: uuid
       */
      mapping_version_id: string;
    };
    /**
     * ParseBatchResponse
     * @description 解析计数与当前版本状态。
     */
    ParseBatchResponse: {
      /** Error Count */
      error_count: number;
      /**
       * File Version Id
       * Format: uuid
       */
      file_version_id: string;
      /** Mapping Version */
      mapping_version: number;
      /**
       * Mapping Version Id
       * Format: uuid
       */
      mapping_version_id: string;
      /** Parsed At */
      parsed_at: string;
      /** Reused Existing */
      reused_existing: boolean;
      /**
       * Status
       * @enum {string}
       */
      status: "parsed" | "parsed_with_errors";
      /** Success Count */
      success_count: number;
      /** Total Rows */
      total_rows: number;
    };
    /**
     * ParseErrorItemResponse
     * @description 解析失败行；raw_json 仅返回给同租户 BATCH_READ 用户。
     */
    ParseErrorItemResponse: {
      /** Parse Error */
      parse_error: string;
      /** Parse Error Code */
      parse_error_code: string;
      parse_error_detail: components["schemas"]["RowErrorDetail"];
      /** Raw Json */
      raw_json: {
        [key: string]: unknown;
      };
      /** Row No */
      row_no: number;
    };
    /** ParseErrorsResponse */
    ParseErrorsResponse: {
      /**
       * File Version Id
       * Format: uuid
       */
      file_version_id: string;
      /** Items */
      items: components["schemas"]["ParseErrorItemResponse"][];
      /** Limit */
      limit: number;
      /**
       * Mapping Version Id
       * Format: uuid
       */
      mapping_version_id: string;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /**
     * ProvenanceMode
     * @description 规范化字段的取值来源。
     * @enum {string}
     */
    ProvenanceMode: "mapped" | "inferred";
    /**
     * ReadinessResponse
     * @description 就绪响应。
     */
    ReadinessResponse: {
      /** Dependencies */
      dependencies: components["schemas"]["DependencyHealth"][];
      /** Ready */
      ready: boolean;
    };
    /** @enum {string} */
    ReasonCode:
      | "limit_exceeded"
      | "invoice_type_not_allowed"
      | "claim_submitted_late"
      | "invoice_title_not_allowed"
      | "invoice_duplicate"
      | "MISSING_REQUIRED_FIELD"
      | "INFERRED_FIELD_NOT_ALLOWED"
      | "RULE_NOT_EFFECTIVE"
      | "RULE_DISABLED"
      | "LIMIT_THRESHOLD_NOT_CONFIGURED"
      | "INVOICE_TYPE_POLICY_NOT_CONFIGURED"
      | "SUBMISSION_BEFORE_EXPENSE_DATE"
      | "TIMELINESS_POLICY_NOT_CONFIGURED"
      | "INVOICE_TITLE_MISSING"
      | "INVOICE_NO_MISSING"
      | "EXEMPTION_MATCHED";
    /**
     * RevisionRequestReason
     * @description 服务层接受的派生原因。
     * @enum {string}
     */
    RevisionRequestReason: "ruleset_change" | "mapping_change";
    /**
     * Role
     * @description RBAC 三角色。权限矩阵定义在 `app.core.security.permissions`。
     * @enum {string}
     */
    Role: "auditor" | "configurator" | "viewer";
    /**
     * RowErrorDetail
     * @description 失败行写入 ``parse_error_detail`` 的版本化结构。
     */
    RowErrorDetail: {
      /** Errors */
      errors: components["schemas"]["FieldError"][];
      /**
       * Mapping Version Id
       * Format: uuid
       */
      mapping_version_id: string;
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: 1;
    };
    /**
     * RowVerdict
     * @enum {string}
     */
    RowVerdict: "passed" | "manual_review" | "flagged";
    RuleDefinition:
      | components["schemas"]["LimitRuleDefinition"]
      | components["schemas"]["InvoiceTypeRuleDefinition"]
      | components["schemas"]["TimelinessRuleDefinition"]
      | components["schemas"]["InvoiceTitleRuleDefinition"]
      | components["schemas"]["InvoiceDuplicateRuleDefinition"];
    RuleEvidence:
      | components["schemas"]["LimitEvidence"]
      | components["schemas"]["InvoiceTypeEvidence"]
      | components["schemas"]["TimelinessEvidence"]
      | components["schemas"]["InvoiceTitleEvidence"]
      | components["schemas"]["InvoiceDuplicateEvidence"];
    /**
     * RuleKind
     * @enum {string}
     */
    RuleKind: "limit" | "invoice_type" | "timeliness" | "invoice_title" | "invoice_duplicate";
    /**
     * RuleOutcome
     * @enum {string}
     */
    RuleOutcome: "passed" | "flagged" | "unavailable" | "exempted";
    /** RuleVersionResponse */
    RuleVersionResponse: {
      /** Config Fingerprint */
      config_fingerprint: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Created By
       * Format: uuid
       */
      created_by: string;
      definition: components["schemas"]["RuleDefinition"];
      /**
       * Effective From
       * Format: date
       */
      effective_from: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Rule Id */
      rule_id: string;
      /** Version */
      version: number;
    };
    /** SaveRuleRequest */
    SaveRuleRequest: {
      definition: components["schemas"]["RuleDefinition"];
      /**
       * Effective From
       * Format: date
       */
      effective_from: string;
      /** Rule Id */
      rule_id: string;
    };
    /** SaveRuleResponse */
    SaveRuleResponse: {
      /** Config Fingerprint */
      config_fingerprint: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Created By
       * Format: uuid
       */
      created_by: string;
      definition: components["schemas"]["RuleDefinition"];
      /**
       * Effective From
       * Format: date
       */
      effective_from: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Reused Existing */
      reused_existing: boolean;
      /** Rule Id */
      rule_id: string;
      /** Version */
      version: number;
    };
    /** SaveSchemaMappingRequest */
    SaveSchemaMappingRequest: {
      availability_thresholds?: components["schemas"]["AvailabilityThresholdsRequest"];
      /** Currency Aliases */
      currency_aliases?: {
        [key: string]: string;
      };
      /**
       * File Version Id
       * Format: uuid
       */
      file_version_id: string;
      /**
       * Inference Rules
       * @default []
       */
      inference_rules: {
        [key: string]: unknown;
      }[];
      /** Mappings */
      mappings: components["schemas"]["MappingEntryRequest"][];
    };
    /** SaveSchemaMappingResponse */
    SaveSchemaMappingResponse: {
      availability_thresholds: components["schemas"]["AvailabilityThresholdsResponse"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Created By */
      created_by: string | null;
      /** Currency Aliases */
      currency_aliases: {
        [key: string]: string;
      };
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Inference Rules */
      inference_rules: (
        | components["schemas"]["ConstantInferenceRule"]
        | components["schemas"]["LiteralLookupInferenceRule"]
      )[];
      /** Is Current For Batch */
      is_current_for_batch: boolean;
      /** Mappings */
      mappings: components["schemas"]["MappingEntryResponse"][];
      /** Reused Existing */
      reused_existing: boolean;
      /** Version */
      version: number;
    };
    /** SchemaMappingsResponse */
    SchemaMappingsResponse: {
      /**
       * File Version Id
       * Format: uuid
       */
      file_version_id: string;
      /** Header Signature */
      header_signature: string;
      /** Source Columns */
      source_columns: string[];
      /** Versions */
      versions: components["schemas"]["MappingVersionResponse"][];
    };
    /** TimelinessEvidence */
    TimelinessEvidence: {
      /** Actual Calendar Days */
      actual_calendar_days?: number | null;
      /** Exemption Id */
      exemption_id?: string | null;
      /** Expense Date */
      expense_date?: string | null;
      /** Expense Type */
      expense_type?: string | null;
      /** Max Calendar Days */
      max_calendar_days?: number | null;
      /**
       * Outcome
       * @enum {string}
       */
      outcome: "flagged" | "unavailable" | "exempted";
      /** Provenance */
      provenance: {
        [key: string]: components["schemas"]["FieldProvenance"];
      };
      reason_code: components["schemas"]["ReasonCode"];
      /** Required Fields */
      required_fields: components["schemas"]["UnifiedField"][];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      rule_kind: "timeliness";
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: 1;
      /** Submission Date */
      submission_date?: string | null;
    };
    /** TimelinessPolicy */
    TimelinessPolicy: {
      /** Expense Type */
      expense_type: string;
      /** Max Calendar Days */
      max_calendar_days: number;
    };
    /** TimelinessRuleDefinition */
    TimelinessRuleDefinition: {
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
      /**
       * Exemptions
       * @default []
       */
      exemptions: components["schemas"]["ExemptionGroup"][];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "timeliness";
      /** Policies */
      policies: components["schemas"]["TimelinessPolicy"][];
      /**
       * Require Direct
       * @default false
       */
      require_direct: boolean;
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: 1;
    };
    /**
     * UnifiedField
     * @description 固定的 12 个统一报销字段，顺序也是稳定输出顺序。
     * @enum {string}
     */
    UnifiedField:
      | "amount"
      | "expense_date"
      | "employee"
      | "expense_type"
      | "invoice_type"
      | "invoice_no"
      | "merchant"
      | "invoice_title"
      | "submission_date"
      | "location"
      | "currency"
      | "description";
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** ValidationSummaryResponse */
    ValidationSummaryResponse: {
      /** Evaluated Row Count */
      evaluated_row_count: number;
      /**
       * File Version Id
       * Format: uuid
       */
      file_version_id: string;
      /** Flagged Count */
      flagged_count: number;
      /** Manual Review Count */
      manual_review_count: number;
      /**
       * Mapping Version Id
       * Format: uuid
       */
      mapping_version_id: string;
      /** Parse Failed Count */
      parse_failed_count: number;
      /** Passed Count */
      passed_count: number;
      /** Reused Existing */
      reused_existing: boolean;
      /** Ruleset Fingerprint */
      ruleset_fingerprint: string;
      /** Total Row Count */
      total_row_count: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  auth_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUser"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  auth_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        eg_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  auth_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        eg_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUser"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  batches_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        eg_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BatchSummaryResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  batches_import: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        eg_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_batches_import"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BatchImportResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  batches_detail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        file_version_id: string;
      };
      cookie?: {
        eg_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BatchDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  batches_field_availability: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        file_version_id: string;
      };
      cookie?: {
        eg_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FieldAvailabilityResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  batches_findings: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
        verdict?: ("flagged" | "manual_review") | null;
      };
      header?: never;
      path: {
        file_version_id: string;
      };
      cookie?: {
        eg_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FindingsResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  batches_parse: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        file_version_id: string;
      };
      cookie?: {
        eg_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ParseBatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ParseBatchResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  batches_parse_errors: {
    parameters: {
      query?: {
        offset?: number;
        limit?: number;
      };
      header?: never;
      path: {
        file_version_id: string;
      };
      cookie?: {
        eg_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ParseErrorsResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  batches_create_revision: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path: {
        file_version_id: string;
      };
      cookie?: {
        eg_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRevisionRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateRevisionResponse"];
        };
      };
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateRevisionResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  batches_validate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        file_version_id: string;
      };
      cookie?: {
        eg_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationSummaryResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  batches_validation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        file_version_id: string;
      };
      cookie?: {
        eg_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationSummaryResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_liveness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LivenessResponse"];
        };
      };
    };
  };
  health_readiness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadinessResponse"];
        };
      };
    };
  };
  rules_list: {
    parameters: {
      query?: {
        rule_id?: string | null;
        latest_only?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: {
        eg_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RuleVersionResponse"][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  rules_save: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        eg_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaveRuleRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SaveRuleResponse"];
        };
      };
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SaveRuleResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  "schema-mappings_list": {
    parameters: {
      query: {
        file_version_id: string;
      };
      header?: never;
      path?: never;
      cookie?: {
        eg_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SchemaMappingsResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  "schema-mappings_save": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        eg_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaveSchemaMappingRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SaveSchemaMappingResponse"];
        };
      };
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SaveSchemaMappingResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
