/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login
     * @description 登录并下发会话 cookie。
     */
    post: operations["auth_login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout
     * @description 登出。
     *
     *     只撤销**本次请求所用的那一个**会话（`auth.session_id` 由认证依赖
     *     精确解析得出），因此同一用户在其它设备上的登录不受影响。
     *
     *     服务端标记 `revoked_at`（UPDATE 而非 DELETE —— 留痕），
     *     同时清掉浏览器 cookie。
     */
    post: operations["auth_logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Me
     * @description 返回当前登录用户。前端用它做路由守卫。
     */
    get: operations["auth_me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/batches": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List
     * @description 列出当前租户批次。
     */
    get: operations["batches_list"];
    put?: never;
    /**
     * Import
     * @description 上传 Excel 并创建或复用文件版本。
     */
    post: operations["batches_import"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/batches/{file_version_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Detail
     * @description 读取批次详情。
     */
    get: operations["batches_detail"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness
     * @description 存活探针。刻意不碰任何外部依赖。
     */
    get: operations["health_liveness"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness
     * @description 就绪探针。并发探测各依赖，任一不可用即整体未就绪。
     */
    get: operations["health_readiness"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * BatchDetailResponse
     * @description 批次详情响应。
     */
    BatchDetailResponse: {
      /** Content Hash */
      content_hash: string;
      /**
       * File Version Id
       * Format: uuid
       */
      file_version_id: string;
      /** Filename */
      filename: string;
      /** Row Count */
      row_count: number;
      /** Rows */
      rows: components["schemas"]["ExpenseRowResponse"][];
      /**
       * Uploaded At
       * Format: date-time
       */
      uploaded_at: string;
      /**
       * Uploaded By
       * Format: uuid
       */
      uploaded_by: string;
    };
    /**
     * BatchImportResponse
     * @description 批次导入响应。
     */
    BatchImportResponse: {
      /** Content Hash */
      content_hash: string;
      /**
       * File Version Id
       * Format: uuid
       */
      file_version_id: string;
      /** Filename */
      filename: string;
      /** Reused Existing */
      reused_existing: boolean;
      /** Row Count */
      row_count: number;
      /** Stored Rows */
      stored_rows: number;
      /**
       * Uploaded At
       * Format: date-time
       */
      uploaded_at: string;
      /**
       * Uploaded By
       * Format: uuid
       */
      uploaded_by: string;
    };
    /**
     * BatchSummaryResponse
     * @description 批次列表项。
     */
    BatchSummaryResponse: {
      /** Content Hash */
      content_hash: string;
      /**
       * File Version Id
       * Format: uuid
       */
      file_version_id: string;
      /** Filename */
      filename: string;
      /** Row Count */
      row_count: number;
      /**
       * Uploaded At
       * Format: date-time
       */
      uploaded_at: string;
      /**
       * Uploaded By
       * Format: uuid
       */
      uploaded_by: string;
    };
    /** Body_batches_import */
    Body_batches_import: {
      /** File */
      file: string;
    };
    /**
     * CurrentUser
     * @description 当前登录用户。
     */
    CurrentUser: {
      /** Permissions */
      permissions: string[];
      role: components["schemas"]["Role"];
      /** Tenant Id */
      tenant_id: string;
      /** User Id */
      user_id: string;
    };
    /**
     * DependencyHealth
     * @description 单个依赖的健康状况。
     */
    DependencyHealth: {
      /** Detail */
      detail?: string | null;
      /** Name */
      name: string;
      status: components["schemas"]["DependencyStatus"];
    };
    /**
     * DependencyStatus
     * @description 依赖状态。
     * @enum {string}
     */
    DependencyStatus: "up" | "down";
    /**
     * ExpenseRowResponse
     * @description 原始报销行摘要。
     */
    ExpenseRowResponse: {
      /** Parse Error */
      parse_error: string | null;
      /** Raw Json */
      raw_json: {
        [key: string]: unknown;
      };
      /** Row No */
      row_no: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * LivenessResponse
     * @description 存活响应。
     */
    LivenessResponse: {
      /** Status */
      status: string;
    };
    /**
     * LoginRequest
     * @description 登录请求。
     */
    LoginRequest: {
      /** Password */
      password: string;
      /**
       * Tenant Slug
       * @default default
       */
      tenant_slug: string;
      /** Username */
      username: string;
    };
    /**
     * ReadinessResponse
     * @description 就绪响应。
     */
    ReadinessResponse: {
      /** Dependencies */
      dependencies: components["schemas"]["DependencyHealth"][];
      /** Ready */
      ready: boolean;
    };
    /**
     * Role
     * @description RBAC 三角色。权限矩阵定义在 `app.core.security.permissions`。
     * @enum {string}
     */
    Role: "auditor" | "configurator" | "viewer";
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  auth_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUser"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  auth_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        eg_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  auth_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        eg_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUser"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  batches_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        eg_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BatchSummaryResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  batches_import: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        eg_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_batches_import"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BatchImportResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  batches_detail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        file_version_id: string;
      };
      cookie?: {
        eg_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BatchDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_liveness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LivenessResponse"];
        };
      };
    };
  };
  health_readiness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadinessResponse"];
        };
      };
    };
  };
}
