"""LangGraph checkpoint 隔离与节点重放测试。

MEMORY.md 把「LangGraph 节点从中断恢复时从头重放」列为已知结构性风险。
本文件是那条风险的**可执行证据**:证明风险真实存在，且缓解措施有效。
"""

import uuid
from collections.abc import AsyncIterator
from typing import Annotated, Any, TypedDict

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from langgraph.checkpoint.postgres.aio import AsyncPostgresSaver
from langgraph.graph import END, START, StateGraph
from psycopg.rows import dict_row
from psycopg_pool import AsyncConnectionPool
from sqlalchemy import func, select, text
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession, async_sessionmaker

from app.core.orchestration.idempotency import process_row_once
from app.core.tenancy.scope import bind_tenant
from app.db.models.audit import AuditLog
from app.db.models.batch import FileVersion, RowResult
from app.db.models.tenancy import AppUser, Role, Tenant

pytestmark = pytest.mark.integration

CHECKPOINT_TABLES = {
    "checkpoints",
    "checkpoint_blobs",
    "checkpoint_writes",
    "checkpoint_migrations",
}
SIDE_EFFECT_ACTION = "test.replay_side_effect"
ROWS_PER_BATCH = 5


@pytest.fixture
async def saver(migrated_db: str) -> AsyncIterator[AsyncPostgresSaver]:
    """已完成建表的 checkpointer，表落在 langgraph schema。"""
    conninfo = migrated_db.replace("postgresql+psycopg://", "postgresql://", 1)
    sep = "&" if "?" in conninfo else "?"
    conninfo = f"{conninfo}{sep}options=-csearch_path%3Dlanggraph"

    pool = AsyncConnectionPool(
        conninfo=conninfo,
        open=False,
        kwargs={"autocommit": True, "prepare_threshold": 0, "row_factory": dict_row},
    )
    await pool.open()
    try:
        instance = AsyncPostgresSaver(pool)  # type: ignore[arg-type]
        await instance.setup()
        yield instance
    finally:
        await pool.close()


async def test_checkpoint_表落在_langgraph_schema(
    saver: AsyncPostgresSaver, engine: AsyncEngine
) -> None:
    """checkpoint 表必须在 langgraph schema，且 public 下不得出现。

    若它们落到 public，Alembic 的 autogenerate 会把它们当成多余表并生成
    `DROP TABLE checkpoints` —— 一次 upgrade 抹掉全部断点数据。
    """
    async with engine.connect() as conn:
        rows = await conn.execute(
            text(
                "SELECT table_schema, table_name FROM information_schema.tables "
                "WHERE table_name = ANY(:names)"
            ).bindparams(names=list(CHECKPOINT_TABLES))
        )
        placement = {name: schema for schema, name in rows}

    assert placement.keys() >= CHECKPOINT_TABLES, (
        f"setup() 后应存在全部 checkpoint 表，实际: {sorted(placement)}"
    )
    in_public = [n for n, s in placement.items() if s == "public"]
    assert not in_public, f"这些 checkpoint 表错误地落在了 public: {in_public}"
    assert all(s == "langgraph" for s in placement.values())


async def test_alembic_不受_checkpoint_表影响(
    saver: AsyncPostgresSaver, alembic_config: Config
) -> None:
    """⚠️ 三层隔离的机械化验证。

    `setup()` 建完 checkpoint 表之后，`alembic check` 必须仍然干净。
    一旦变红，说明隔离失效，下一次 autogenerate 就会生成删表语句。
    """
    try:
        command.check(alembic_config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover
        pytest.fail(
            f"checkpointer.setup() 之后 Alembic 检测到差异，说明 checkpoint 表"
            f"泄漏进了 Alembic 的可见范围: {exc}"
        )


class BatchState(TypedDict):
    """测试用图的状态。"""

    processed: Annotated[list[int], lambda a, b: a + b]


async def _seed(session: AsyncSession) -> tuple[uuid.UUID, uuid.UUID]:
    tenant = Tenant(slug=f"t-{uuid.uuid4().hex[:8]}", name="重放测试租户")
    session.add(tenant)
    await session.flush()
    user = AppUser(
        tenant_id=tenant.id,
        username="tester",
        password_hash="x",
        role=Role.AUDITOR,
        is_active=True,
    )
    session.add(user)
    await session.flush()
    fv = FileVersion(
        tenant_id=tenant.id,
        filename="b.xlsx",
        content_hash=uuid.uuid4().hex * 2,
        uploaded_by=user.id,
    )
    session.add(fv)
    await session.commit()
    return tenant.id, fv.id


@pytest.mark.usefixtures("clean_db")
async def test_节点重放不产生重复副作用(
    saver: AsyncPostgresSaver,
    session_factory: async_sessionmaker[AsyncSession],
) -> None:
    """本文件的核心测试 —— 三重断言。

    模拟 PRD 的「中断恢复」流程:处理中断后重新触发同一个 file_version_id，
    系统查行级结果表，已完成行跳过。

    用**两个独立计数器**分别观测两件事:

      1. `node_runs` —— 节点体执行了几次
         → 断言 == 2，证明风险真实存在:节点确实被完整重跑了

      2. `compute_calls` —— 实际的行处理逻辑执行了几次
         → 断言 == 行数，证明 `process_row_once` 的守卫拦住了重复执行

      3. 数据库里 row_result 与 audit_log 各恰好等于行数
         → 证明已提交副作用没有重复

    三条缺一不可。只断言 3 的话，若哪天节点不再重跑，测试依然会绿——
    那时它验证的就不再是幂等机制，而是一个无声失效的测试。
    只断言 1、2 的话，则证明不了副作用真的落库正确。
    """
    async with session_factory() as setup_session:
        tenant_id, fv_id = await _seed(setup_session)

    node_runs = 0
    compute_calls = 0

    async def process_batch(state: BatchState) -> BatchState:
        """处理整批行的节点。每次节点执行都会完整跑一遍。"""
        nonlocal node_runs
        node_runs += 1
        done: list[int] = []
        async with session_factory() as session:
            bind_tenant(session.sync_session, tenant_id)
            for row_no in range(1, ROWS_PER_BATCH + 1):

                async def compute(n: int = row_no) -> tuple[str, str]:
                    nonlocal compute_calls
                    compute_calls += 1
                    session.add(
                        AuditLog(
                            tenant_id=tenant_id,
                            action=SIDE_EFFECT_ACTION,
                            target_type="row",
                            target_id=str(n),
                        )
                    )
                    await session.flush()
                    return ("ok", "v1")

                await process_row_once(
                    session,
                    tenant_id=tenant_id,
                    file_version_id=fv_id,
                    row_no=row_no,
                    compute=compute,
                )
                done.append(row_no)
            await session.commit()
        return {"processed": done}

    builder: StateGraph[BatchState, None, BatchState, BatchState] = StateGraph(BatchState)
    builder.add_node("process", process_batch)
    builder.add_edge(START, "process")
    builder.add_edge("process", END)
    graph = builder.compile(checkpointer=saver)

    # thread_id = file_version_id —— 恢复语义的锚点
    config: Any = {"configurable": {"thread_id": str(fv_id)}}

    await graph.ainvoke({"processed": []}, config)
    assert node_runs == 1
    assert compute_calls == ROWS_PER_BATCH

    # —— 恢复:用相同 thread_id 再次触发，模拟中断后重跑该批次 ——
    await graph.ainvoke({"processed": []}, config)

    # 断言 1:节点体确实被完整重跑了（风险真实存在）
    assert node_runs == 2, (
        f"节点体应被执行 2 次，实际 {node_runs} 次 —— "
        f"没有发生重跑，本测试失去意义，需要重新构造恢复场景"
    )

    # 断言 2:但行处理逻辑没有重复执行（守卫生效）
    assert compute_calls == ROWS_PER_BATCH, (
        f"compute 应仍为 {ROWS_PER_BATCH} 次，实际 {compute_calls} 次 —— "
        f"process_row_once 的守卫失效，已完成行被重新处理了"
    )

    # 断言 3:已提交的数据库副作用没有重复
    async with session_factory() as check:
        bind_tenant(check.sync_session, tenant_id)

        row_results = await check.scalar(
            select(func.count()).select_from(RowResult).where(RowResult.file_version_id == fv_id)
        )
        assert row_results == ROWS_PER_BATCH, (
            f"row_result 应恰好 {ROWS_PER_BATCH} 行，实际 {row_results} —— 幂等失效"
        )

        for row_no in range(1, ROWS_PER_BATCH + 1):
            side_effects = await check.scalar(
                select(func.count())
                .select_from(AuditLog)
                .where(AuditLog.action == SIDE_EFFECT_ACTION)
                .where(AuditLog.target_id == str(row_no))
            )
            assert side_effects == 1, (
                f"第 {row_no} 行的审计副作用应恰好 1 条，实际 {side_effects} 条 —— "
                f"节点重放导致副作用重复，这正是幂等机制要防的事"
            )
