"""tier B skeleton tables

骨架层:schema_mapping / rule_config / policy_document / policy_clause /
finding / correlation_finding / evidence_step / review / sampling_audit /
field_availability / capability_declaration。

与 0001 的区别:这一层只建「结构 + 规格明写的约束」，不猜测特性列。
细节列随对应 feature 用加列迁移补——那时才知道要哪些字段。

⚠️ 本迁移建立的唯一约束同样属于 AGENTS.md 的**受保护区域**。
后续 feature 迁移只允许 ADD COLUMN / ADD INDEX，
**不得 DROP 或放宽本文件中的任何 UNIQUE / CHECK 约束。**

其中必须现在就存在、不能推迟到对应 feature 的:
  - review    的 unique(finding_id)                  —— 防重复复核。
    复核结论是回流评测集唯一的真实标签来源，重复会直接污染评测。
  - rule_config 的 unique(tenant_id, rule_id, version) —— 规则版本化，
    「相同输入 + 相同规则版本 → 相同输出」这一可复现性承诺的前提。
  - evidence_step 的 unique(finding_id, step_no)     —— ReAct 循环同样会重放。
  - finding   的 severity_impact / severity_confidence **两列分开**
    并各带 CHECK(0..3) —— 二维分级是规格明写的，事后拆列要迁移数据。
  - policy_clause.text NOT NULL —— 条款原文是逐字引用校验的比对源，
    是地基而非 F4 的实现细节。
  - sampling_audit 整张表 —— 被放行样本随机抽检是漏放率**唯一**可测来源，
    必须在第一个批次就能用，不是后续优化项。

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-27

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "policy_document",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("source_filename", sa.String(length=512), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_policy_document_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_document")),
        sa.UniqueConstraint(
            "tenant_id", "title", "version", name=op.f("uq_policy_document_tenant_id_title_version")
        ),
    )
    op.create_index(
        op.f("ix_policy_document_tenant_id"), "policy_document", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_policy_document_tenant_id_effective_date",
        "policy_document",
        ["tenant_id", "effective_date"],
        unique=False,
    )
    op.create_table(
        "rule_config",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.String(length=128), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_rule_config_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_config")),
        sa.UniqueConstraint(
            "tenant_id", "rule_id", "version", name=op.f("uq_rule_config_tenant_id_rule_id_version")
        ),
    )
    op.create_index(op.f("ix_rule_config_tenant_id"), "rule_config", ["tenant_id"], unique=False)
    op.create_table(
        "schema_mapping",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_column", sa.String(length=255), nullable=False),
        sa.Column("target_field", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_schema_mapping_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schema_mapping")),
        sa.UniqueConstraint(
            "tenant_id",
            "source_column",
            "version",
            name=op.f("uq_schema_mapping_tenant_id_source_column_version"),
        ),
    )
    op.create_index(
        op.f("ix_schema_mapping_tenant_id"), "schema_mapping", ["tenant_id"], unique=False
    )
    op.create_table(
        "policy_clause",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("clause_no", sa.String(length=64), nullable=False),
        sa.Column("hierarchy_path", sa.String(length=1024), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["policy_document.id"],
            name=op.f("fk_policy_clause_document_id_policy_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_policy_clause_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_clause")),
        sa.UniqueConstraint(
            "document_id", "clause_no", name=op.f("uq_policy_clause_document_id_clause_no")
        ),
    )
    op.create_index("ix_policy_clause_document_id", "policy_clause", ["document_id"], unique=False)
    op.create_index(
        op.f("ix_policy_clause_tenant_id"), "policy_clause", ["tenant_id"], unique=False
    )
    op.create_table(
        "capability_declaration",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("file_version_id", sa.Uuid(), nullable=False),
        sa.Column("detector", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "enabled",
                "degraded",
                "unavailable",
                name="capability_status_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_version_id", "tenant_id"],
            ["file_version.id", "file_version.tenant_id"],
            name=op.f("fk_capability_declaration_file_version_id_tenant_id_file_version"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_capability_declaration_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capability_declaration")),
        sa.UniqueConstraint(
            "file_version_id",
            "detector",
            name=op.f("uq_capability_declaration_file_version_id_detector"),
        ),
    )
    op.create_index(
        "ix_capability_declaration_file_version_id",
        "capability_declaration",
        ["file_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_capability_declaration_tenant_id"),
        "capability_declaration",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "correlation_finding",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("file_version_id", sa.Uuid(), nullable=False),
        sa.Column("detector", sa.String(length=64), nullable=False),
        sa.Column("participating_row_nos", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("evidence_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("severity_impact", sa.Integer(), nullable=False),
        sa.Column("severity_confidence", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_version_id", "tenant_id"],
            ["file_version.id", "file_version.tenant_id"],
            name=op.f("fk_correlation_finding_file_version_id_tenant_id_file_version"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_correlation_finding_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_correlation_finding")),
    )
    op.create_index(
        "ix_correlation_finding_file_version_id",
        "correlation_finding",
        ["file_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_correlation_finding_tenant_id"), "correlation_finding", ["tenant_id"], unique=False
    )
    op.create_table(
        "field_availability",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("file_version_id", sa.Uuid(), nullable=False),
        sa.Column("field_name", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "available", "inferred", "missing", name="field_status_enum", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_version_id", "tenant_id"],
            ["file_version.id", "file_version.tenant_id"],
            name=op.f("fk_field_availability_file_version_id_tenant_id_file_version"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_field_availability_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_availability")),
        sa.UniqueConstraint(
            "file_version_id",
            "field_name",
            name=op.f("uq_field_availability_file_version_id_field_name"),
        ),
    )
    op.create_index(
        op.f("ix_field_availability_file_version_id"),
        "field_availability",
        ["file_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_field_availability_tenant_id"), "field_availability", ["tenant_id"], unique=False
    )
    op.create_table(
        "finding",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("file_version_id", sa.Uuid(), nullable=False),
        sa.Column("row_no", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("severity_impact", sa.Integer(), nullable=False),
        sa.Column("severity_confidence", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.String(length=128), nullable=True),
        sa.Column("rule_version", sa.String(length=64), nullable=True),
        sa.Column("clause_id", sa.Uuid(), nullable=True),
        sa.Column("quote", sa.Text(), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity_confidence >= 0 AND severity_confidence <= 3",
            name=op.f("ck_finding_severity_confidence_range"),
        ),
        sa.CheckConstraint(
            "severity_impact >= 0 AND severity_impact <= 3",
            name=op.f("ck_finding_severity_impact_range"),
        ),
        sa.ForeignKeyConstraint(
            ["clause_id"],
            ["policy_clause.id"],
            name=op.f("fk_finding_clause_id_policy_clause"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["file_version_id", "tenant_id"],
            ["file_version.id", "file_version.tenant_id"],
            name=op.f("fk_finding_file_version_id_tenant_id_file_version"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_finding_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finding")),
    )
    op.create_index(
        "ix_finding_file_version_id_severity",
        "finding",
        ["file_version_id", "severity_impact"],
        unique=False,
    )
    op.create_index(op.f("ix_finding_tenant_id"), "finding", ["tenant_id"], unique=False)
    op.create_table(
        "sampling_audit",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("file_version_id", sa.Uuid(), nullable=False),
        sa.Column("row_no", sa.Integer(), nullable=False),
        sa.Column(
            "sampled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "decision",
            sa.Enum("confirmed", "false_positive", name="review_decision_enum", native_enum=False),
            nullable=True,
        ),
        sa.Column("reviewer_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_version_id", "tenant_id"],
            ["file_version.id", "file_version.tenant_id"],
            name=op.f("fk_sampling_audit_file_version_id_tenant_id_file_version"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["app_user.id"],
            name=op.f("fk_sampling_audit_reviewer_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_sampling_audit_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sampling_audit")),
        sa.UniqueConstraint(
            "file_version_id", "row_no", name=op.f("uq_sampling_audit_file_version_id_row_no")
        ),
    )
    op.create_index(
        "ix_sampling_audit_file_version_id", "sampling_audit", ["file_version_id"], unique=False
    )
    op.create_index(
        op.f("ix_sampling_audit_tenant_id"), "sampling_audit", ["tenant_id"], unique=False
    )
    op.create_table(
        "evidence_step",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("step_no", sa.Integer(), nullable=False),
        sa.Column("tool_name", sa.String(length=128), nullable=False),
        sa.Column("tool_input", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tool_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["finding.id"],
            name=op.f("fk_evidence_step_finding_id_finding"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_evidence_step_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_step")),
        sa.UniqueConstraint(
            "finding_id", "step_no", name=op.f("uq_evidence_step_finding_id_step_no")
        ),
    )
    op.create_index(
        "ix_evidence_step_finding_id_step_no",
        "evidence_step",
        ["finding_id", "step_no"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_step_tenant_id"), "evidence_step", ["tenant_id"], unique=False
    )
    op.create_table(
        "review",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum("confirmed", "false_positive", name="review_decision_enum", native_enum=False),
            nullable=False,
        ),
        sa.Column("reviewer_id", sa.Uuid(), nullable=False),
        sa.Column(
            "reviewed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["finding.id"],
            name=op.f("fk_review_finding_id_finding"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["app_user.id"],
            name=op.f("fk_review_reviewer_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_review_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review")),
        sa.UniqueConstraint("finding_id", name=op.f("uq_review_finding_id")),
    )
    op.create_index(op.f("ix_review_tenant_id"), "review", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_tenant_id"), table_name="review")
    op.drop_table("review")
    op.drop_index(op.f("ix_evidence_step_tenant_id"), table_name="evidence_step")
    op.drop_index("ix_evidence_step_finding_id_step_no", table_name="evidence_step")
    op.drop_table("evidence_step")
    op.drop_index(op.f("ix_sampling_audit_tenant_id"), table_name="sampling_audit")
    op.drop_index("ix_sampling_audit_file_version_id", table_name="sampling_audit")
    op.drop_table("sampling_audit")
    op.drop_index(op.f("ix_finding_tenant_id"), table_name="finding")
    op.drop_index("ix_finding_file_version_id_severity", table_name="finding")
    op.drop_table("finding")
    op.drop_index(op.f("ix_field_availability_tenant_id"), table_name="field_availability")
    op.drop_index(op.f("ix_field_availability_file_version_id"), table_name="field_availability")
    op.drop_table("field_availability")
    op.drop_index(op.f("ix_correlation_finding_tenant_id"), table_name="correlation_finding")
    op.drop_index("ix_correlation_finding_file_version_id", table_name="correlation_finding")
    op.drop_table("correlation_finding")
    op.drop_index(op.f("ix_capability_declaration_tenant_id"), table_name="capability_declaration")
    op.drop_index("ix_capability_declaration_file_version_id", table_name="capability_declaration")
    op.drop_table("capability_declaration")
    op.drop_index(op.f("ix_policy_clause_tenant_id"), table_name="policy_clause")
    op.drop_index("ix_policy_clause_document_id", table_name="policy_clause")
    op.drop_table("policy_clause")
    op.drop_index(op.f("ix_schema_mapping_tenant_id"), table_name="schema_mapping")
    op.drop_table("schema_mapping")
    op.drop_index(op.f("ix_rule_config_tenant_id"), table_name="rule_config")
    op.drop_table("rule_config")
    op.drop_index("ix_policy_document_tenant_id_effective_date", table_name="policy_document")
    op.drop_index(op.f("ix_policy_document_tenant_id"), table_name="policy_document")
    op.drop_table("policy_document")
    # ### end Alembic commands ###
